### ISSUE TITLE
Makefile restore function

### ISSUE THREAD

**Issue by yuzhou-pan** [s-wien/data550-finalproject#1]
When I run `make install`, there are some errors:

![image](https://github.com/s-wien/data550-finalproject/assets/49797609/4463b70f-819a-4cf3-9a53-2b88e02f1549)

But after I removed the `prompt = FALSE` option in `renv::restore()`, everything works fine and I can make the report.html successfully.

**Comment by s-wien** [comment]
Removed `prompt = FALSE` option in `renv::restore()` in the `Makefile`, thank you for spotting this!
